### ISSUE TITLE
Search link error

### ISSUE THREAD

**Issue by jpontem** [cvtienhoven/graylog-plugin-aggregates#1]
The search link of the alert mails is incorrect.
Example of wrong generated link:
**null**/search?rangetype=absolute&fields=message%2Csource%2Creq_remoteHost&from=2016-08-23T14:13:59.817Z&to=2016-08-23T14:14:59.817Z&q=level%3A3+AND+file%3Axxxx+AND+host%3A%22yyyyy%22

**Comment by funkdoobiest** [comment]
@jpontem I had the same problem. I set "transport_email_web_interface_url" in graylog "server.conf" and now it's working.

**Comment by cvtienhoven** [comment]
Yes the creation of the link relies on the email transport configuration, just as you would configure it for the Email Alarm Callback. So setting transport_email_web_interface_url correctly will fix your problem. I'll add a note in the README.md, thank both of you for your feedback.
