### ISSUE TITLE
Problem of understanding

### ISSUE THREAD

**Issue by artphrases** [cvtienhoven/graylog-plugin-aggregates#10]
I don`t unterstand the "query" field of your plugin. Is the "invalid user" (shown in the picture) a predefined query? Or is it a saved search? Could you give some more examples or explanations on this. Thank you very much.

**Comment by cvtienhoven** [comment]
Hi @artphrases, the query field is the Lucene query that will be fired to Elasticsearch. Instead of the text search `invalid user` you could also enter something like `source: yourhostname.domain`, just like you would do in the Graylog search bar.

**Comment by cvtienhoven** [comment]
Hi @artphrases, I'm closing this issue in the assumption that my answer was sufficient. If that's not the case, please re-open this one or open another issue.

**Comment by artphrases** [comment]
Hi,

 

yes, please close. Thanks for your answer.

 

Best regards

Martin

 

Gesendet: Donnerstag, 11. Mai 2017 um 08:17 Uhr
Von: cvtienhoven <notifications@github.com>
An: cvtienhoven/graylog-plugin-aggregates <graylog-plugin-aggregates@noreply.github.com>
Cc: artphrases <phrases@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [cvtienhoven/graylog-plugin-aggregates] Problem of understanding (#10)


Hi @artphrases, I'm closing this issue in the assumption that my answer was sufficient. If that's not the case, please re-open this one or open another issue.
