### ISSUE TITLE
Match criterium "less than" does not work correctly when there are no logs in search interval

### ISSUE THREAD

**Issue by jurivanco** [cvtienhoven/graylog-plugin-aggregates#11]
Match criterium "less than" does not work correctly when there are no logs in search interval.
## Expected behavior
Aggregate Rule is triggered everytime, when the count of messages (searched by Query and aggregated by Field) is less than defined number of Matches in time Interval.
## Actual behavior
Aggregate Rule is triggered when the aggregated count of logs is between 1 and the defined match count.
## Steps to reproduce the problem
1. Create aggregated rule with setup: `Match more or equal = Less`, `Matches = 3`, `Interval = 5` minutes.
2. Send 3 logs to Graylog in 5 minutes interval. Alert is not triggered, correct.
3. Send 1 or 2 logs in another 5 minutes interval.  Alert is triggered, correct.
4. Do not send any logs in another 5 minutes interval.  Alert is not triggered, incorrect (count 0 is less than expected 3 matched).

**Comment by cvtienhoven** [comment]
Hi @jurivanco, thanks for your comment. I'm aware of this behavior, I chose to leave it this way for the time being, as it would potentially result in a lot of alerts, e.g. every minute for instance while there's no query result. If I'm going to fix this, I would also have to add a grace period for the alerting, so you won't get spammed :) I'll put it on the agenda ;)
