### ISSUE TITLE
Add other alert methods e.g. HTTP call

### ISSUE THREAD

**Issue by Bendolfc** [cvtienhoven/graylog-plugin-aggregates#16]
Hi,

Just a quick suggestion if I may, it would be really useful if there was an option to make a HTTP call similar to how alerting in the core product works, in my case when an alert is triggered, it would be useful it we could initiate a HTTP call that can then do some other tasks.

**Comment by cvtienhoven** [comment]
Hi @Bendolfc, thanks for your suggestion I was thinking about that feature myself, to integrate the plugin more tightly with Graylog. I don't know when I could provide such functionality, but I'll keep you updated in this issue.

**Comment by jothoma1** [comment]
Another suggestion is to be able to launch your other plugin : sensu alerting :)
Thanks for your work !

**Comment by artphrases** [comment]
Hi, as Bendolfc already mentioned we also would like to use your plugin with the possibility to make HTTP calls that Icinga2 can read this. Could you give us some advice, what we have to tell our devolpers that they are able to extend your plugin. Thanks in advance Martin

**Comment by cvtienhoven** [comment]
Hi @artphrases, thanks for your response. I'd say wait a little bit until the next release, I'm currently implementing the feature of using the native Graylog Alarm callbacks (Notifications). The current way of alerting (by email) will disappear in favor of using the Email Callback (or any other callback of your choice, like HTTP). I hope to have stuff finished about next week or so (but please don't shoot me if it gets a bit later ;) ).

**Comment by artphrases** [comment]
Dear cvtienhoven,

 

these are great news. Thanks for this!

 

Best regards

Martin

 

 

Gesendet: Dienstag, 01. August 2017 um 21:50 Uhr
Von: cvtienhoven <notifications@github.com>
An: cvtienhoven/graylog-plugin-aggregates <graylog-plugin-aggregates@noreply.github.com>
Cc: artphrases <phrases@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [cvtienhoven/graylog-plugin-aggregates] Add other alert methods e.g. HTTP call (#16)


Hi @artphrases, thanks for your response. I'd say wait a little bit until the next release, I'm currently implementing the feature of using the native Graylog Alarm callbacks (Notifications). The current way of alerting (by email) will disappear in favor of using the Email Callback (or any other callback of your choice, like HTTP). I hope to have stuff finished about next week or so (but please don't shoot me if it gets a bit later ;) ).

**Comment by cvtienhoven** [comment]
Hey guys, I just released version 2.0.0 of the plugin, in which the native Notifications can be (have to be) used to generate alerts. Take it on a test drive I'd say :)

**Comment by Bendolfc** [comment]
Hi,

I have installed the latest pluging and it looks great thanks, however I am not sure if it is intended behaviour or if I am configuring it incorrectly, when I setup a HTTP callback, it doesn't include any useful data that can be used to act upon, all it seems to contain is the rule name but doesn't include the IP address, number of occurences or even the search that could be used to get them.

There is a "matching_messages" key but that is empty.

Email alerts are working fine with all the required info,

**Comment by shumbashi** [comment]
+1 to @Bendolfc, I'm also experiencing the same where the "matching_messages": [] is empty and thus there is no useful content in the HTTP post to act upon.
