### ISSUE TITLE
Emailed link issue

### ISSUE THREAD

**Issue by Bendolfc** [cvtienhoven/graylog-plugin-aggregates#2]
Hi,

Great plugin thanks, really appreciate it, one problem I have noticed is the email link does not include the stream so only admin users are able to click on the link and have it show the search results. Normal users are just redirected to the streams page.

E.g. 

http://url:9000/search? 
should be 
http://url:9000/streams/5321e786e4b0f775c3877408/search?

**Comment by cvtienhoven** [comment]
Thanks for your input, I'll fix it in the next release.

**Comment by cvtienhoven** [comment]
I released version 0.0.13 for this, that should fix this issue. If not, feel free to reopen this issue. Thanks again!
