### ISSUE TITLE
not able to select notification type --No Notification--

### ISSUE THREAD

**Issue by Manjukb** [cvtienhoven/graylog-plugin-aggregates#20]
while creating rules no notification in select box

**Comment by cvtienhoven** [comment]
Did you follow this concept as described in the README? 

> Since version 2.0.0, the plugin integrates tightly with the Notifications within Graylog. You can define a notification on a stream as you would normally do, and from within the plugin, you can refer to that notification as well, as long as you use the same stream for the aggregate rule.

**Comment by Manjukb** [comment]
can you please elaborate what i must do?? 
as of now i just downloaded the jar and placed in plugin folder
please let me know what configuration i need to do

**Comment by cvtienhoven** [comment]
No configuration, just plain usage of Graylog. If you don't understand the tool yet, read the docs first (http://docs.graylog.org/en/2.3/)

What you need to do in this case is:
1 Define a stream (http://docs.graylog.org/en/2.3/pages/streams.html#how-do-i-create-a-stream)
2 Create a notification for that stream (http://docs.graylog.org/en/2.3/pages/streams/alerts.html#notifications)
3 Create an Aggregate rule and select the stream you created in step 1
4 Select the notification you created in step 2

**Comment by Manjukb** [comment]
oh got it 
thanks man
