### ISSUE TITLE
Triggered Alerts have title "Unknown alert"

### ISSUE THREAD

**Issue by kiview** [cvtienhoven/graylog-plugin-aggregates#25]
All alerts triggered by the plugin have the title "Unknown alert". I've provided a screenshot.
Also the type is unknown (which might be okay?).
Running Graylog 2.3

I've provided a screenshot:
![alerts](https://user-images.githubusercontent.com/5088104/30208882-b7646656-9495-11e7-81e6-782590c08509.png)

**Comment by cvtienhoven** [comment]
Yep, I'm aware of this behavior in the SNAPSHOT version. Working on it.

**Comment by cvtienhoven** [comment]
This should be fixed in version 2.1.0 of the plugin.
