### ISSUE TITLE
Any way to suppress [AggregatesMaintenance] removed 0 history items

### ISSUE THREAD

**Issue by 123dev** [cvtienhoven/graylog-plugin-aggregates#26]
Will it be possible to suppress the following messages appearing in Graylog logs every minute?
[AggregatesMaintenance] removed 0 history items

Perhaps the log level can be changed from **Info** to **Debug**

Thanks

**Comment by andbus** [comment]
It's important to make changes very carefully. 

Previous (2.0.1) version used to generate log alerts as [Aggregates]:
2017-08-27T07:08:08.389+02:00 INFO  [Aggregates] 154 found for SubjectUserNameDelete=username

Newer (2.1.0) has changed it to [AggregatesAlertCondition]:
2017-10-05T15:15:13.718+02:00 INFO  [AggregatesAlertCondition] 34 found for SubjectUserNameRead=username

It would be very helpful if such a changes could be announce as release notes or something else. I'm using this logs to extract count of founds.

**Comment by cvtienhoven** [comment]
@andbus There's a changelog in the README that you can check for changes. The change you mention is part of the following:

> Fully integrated alerting with the native Graylog notifications method, including message backlog (#24, #25)

That's a big change, please forgive me that I can't mention every change of a log line / logging class. It would take longer to write the change log than to actually implement the change :)

Btw, if you're dependent on such logging and ask yourself what's needed for an upgrade, nothing stands in your way to peek into the class that logs your line and check if something changed.

@123dev I'll take it into consideration, it's a rather repetitive message that doesn't really tell much useful about business logic.

**Comment by 123dev** [comment]
@cvtienhoven 
Thanks for taking this into consideration. :)

**Comment by cvtienhoven** [comment]
This has been fixed in version 2.3.0. The message is now logged at debug level.
