### ISSUE TITLE
404 when deleting/edit/disable aggregations with "/" in the name

### ISSUE THREAD

**Issue by alcampos** [cvtienhoven/graylog-plugin-aggregates#3]
When i tried to delete, edit or disable an aggregation that i created with a "/" in the name it fails. Here the requests.

> DELETE /api/plugins/org.graylog.plugins.aggregates/rules/somethingwithslash/in/the/name HTTP/1.1
> Host: example.com
> Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Origin: https://example.com
> Accept-Encoding: gzip, deflate, sdch, br
> Accept-Language: es-ES,es;q=0.8,en;q=0.6
> User-Agent: Chrome/55.0.2883.95 Safari/537.36
> Content-Type: application/json
> Accept: application/json
> Referer: https://example.com/aggregates
> X-Requested-With: XMLHttpRequest
> Connection: keep-alive

< HTTP/1.1 404 Not Found
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Authorization, Content-Type, X-Graylog-No-Session-Extension, X-Requested-With
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Origin: https://example.com
< Access-Control-Max-Age: 600
< Cache-Control: no-cache
< Content-Type: application/json
< Date: Tue, 31 Jan 2017 12:28:33 GMT
< Server: nginx/1.10.1
< X-Graylog-Node-ID: xxxxxxxxxxxxxxxxxxxxxxxxxxx
< Content-Length: 50
< Connection: keep-alive

Maybe it is saving the aggregation without URL encoding and then trying to look it up without URL encoding.

**Comment by cvtienhoven** [comment]
Thanks for taking the time to submit this issue. You were right, the encoding didn't happen while communication with the REST API. I fixed this in version 0.0.14, you might need to clear your browser cache to make it work.
