### ISSUE TITLE
url prefix ignored

### ISSUE THREAD

**Issue by fragfutter** [cvtienhoven/graylog-plugin-aggregates#34]
proxying graylog with a prefix

rest_listen_uri = http://127.0.0.1:9000/graylog/api
web_listen_uri = http://127.0.0.1:9000/graylog

so graylog is reachable via

http://some.server/graylog/

This prefix is ignored by the aggregate plugin.

Graylog -> Aggregates -> manage report schedules 

results in

http://some.server/aggregates/schedules

**Comment by cvtienhoven** [comment]
Hi @fragfutter, could you please try if release 2.2.4 works for you? Thanks!

**Comment by fragfutter** [comment]
confirming that  plugin version 2.24 with graylog 2.4.5 works.
