### ISSUE TITLE
[Request] Adding possibility to configure Report in PDF

### ISSUE THREAD

**Issue by BlackPearl01** [cvtienhoven/graylog-plugin-aggregates#4]
Hello,

First, thank you for your plugin for GrayLog! It's useful and help me to create some alerts in GrayLog.

The PDF report are very useful too! But as you had write, for the moment, the configuration of intervals, schedules etc. for reports is not possible yet.

Have you an idea of the date when you can develop and include this feature in your plugin?

Thank you again,

**Comment by cvtienhoven** [comment]
Hey, thanks for reaching out and for using the plugin. I'll definitely implement those features, but it's hard to give a schedule because stuff is very busy at my side. But I'll do my best, just keep an eye on this repo.

**Comment by BlackPearl01** [comment]
Hi,

Thank you for your answer! Can't wait to try this! Good luck for the dev :)

**Comment by cvtienhoven** [comment]
@BlackPearl01: I added the reporting schedule feature in version 1.0.0, so please feel free to take that one for a test drive.

**Comment by BlackPearl01** [comment]
Hi!

I can't test now but I really want to thank you for your work!
