### ISSUE TITLE
[REQUEST] Users can still see the Aggregates Menu even when they do not have permission.

### ISSUE THREAD

**Issue by DerPhlipsi** [cvtienhoven/graylog-plugin-aggregates#40]
Heyo,

just a little cosmetic issue. Users that do not have any permissions for the Aggregates plugin still have the menu option for Aggregates, that leads to an empty page. Maybe the menu option should be made visible only, when the user has at least the read permission.

Greetings,
Philipp

**Comment by cvtienhoven** [comment]
This should be fixed in version 2.3.0. If not, please re-open this issue.
