### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by vipul-mykaarma** [cvtienhoven/graylog-plugin-aggregates#45]
Hi i tried to install your plugin , but its not getting installed. Version of graylog is 2.4.6 . Copied the plu
![Uploading Screen Shot 2018-11-05 at 12.00.19 PM.png…]()
gin into plugins folder and restarted the graylog server but to no avail

**Comment by PeepOks** [comment]
I had same problem. I managed to solve it by installing plugin from RPM package.

**Comment by cvtienhoven** [comment]
Because of lack of activity I'm closing this issue.
