### ISSUE TITLE
Tested against 2.5

### ISSUE THREAD

**Issue by jebucha** [cvtienhoven/graylog-plugin-aggregates#46]
Have you perchance tested the plugin against Graylog 2.5? I updated my test system to Graylog 2.5.0-3 and was getting a could not post http 400 error when attempting to create or edit any aggregate rules. Nothing mentioned in the Graylog server.log unfortunately.

**Comment by mcapra** [comment]
Rebuilding this plugin against the [2.5 libraries](https://github.com/Graylog2/graylog2-server/tree/2.5) seems to solve this issue.

**Comment by cvtienhoven** [comment]
Haven't got the chance yet to test it against Graylog 2.5 unfortunately. I'll have a look what's going on, perhaps I'll build a release against the 2.5 libraries for this as @mcapra tested.

**Comment by jebucha** [comment]
@cvtienhoven Understandable sir, appreciate any time you are able to put into this.
@mcapra It appears that the plugin is not compatible with pre-2.5 versions of Graylog. I tested it against 2.4.6 just now and received errors just loading the page.
![screen shot 2019-01-03 at 10 12 35](https://user-images.githubusercontent.com/18007771/50648308-7cf0f300-0f40-11e9-9960-69a5e7890973.png)

**Comment by jebucha** [comment]
Oh also, I can comfirm that the jar @mcapra built against the 2.5 libraries appears to be fully functional on Graylog 2.5/2.5.1.

**Comment by cvtienhoven** [comment]
@jebucha @mcapra hey guys, I just released version 2.4.0, which is built against version 2.5.1 (and includes some bug fixes). Could you perhaps give it a test drive against your 2.5 Graylog instances? @jebucha as you indicated, this version will probably not be compatible with 2.4.x, so I added the constraint for that in the plugin. Thanks!

**Comment by jebucha** [comment]
@cvtienhoven Can confirm that 2.4.0 works with Graylog 2.5.1, thanks again.

**Comment by cvtienhoven** [comment]
@jebucha thanks for checking! Closing this one.
