### ISSUE TITLE
Searches from Reports not including Escape characters when clicking Search

### ISSUE THREAD

**Issue by ion-storm** [cvtienhoven/graylog-plugin-aggregates#6]
I have ransomware alerting enabled with your addon, when a directory like "C:\Users\kweller\Desktop\help_decrypt_testing_graylog_test_3.txt" is detected the \'s are not escaped as well as the ":"
Thanks

**Comment by cvtienhoven** [comment]
Hey @ion-storm, what does your rule look like and what do you expect exactly? Escaping the query automatically in the plugin can have unwanted side-effects for users that escape the special characters themselves.

**Comment by cvtienhoven** [comment]
I'm going to close this issue due to lack of response.
